version: "3"

services:
  mssql:
    # container_name: mssql
    # image: mcr.microsoft.com/mssql/server:2019-latest
    build: ./build/mssql
   # image: my_mssql:latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_MEMORYLIMIT_MB=1300
    ports:
      - "5434:1433"
    volumes:
      - mssqlvolume:/var/opt/mssql

volumes:
  mssqlvolume: