version: "3"

services:
  
  # CFML Engine
  cfml:
    # container_name: cfml
    image: ortussolutions/commandbox:lucee5
   
    # bind public port to 8080
    ports:
      - "8080:8080"
   
    volumes:
    - .:/app
   
    environment:
      PORT: 8080
      SSL_PORT: 8443
      BOX_SERVER_CFCONFIGFILE: /app/.cfconfig.json
      BOX_SERVER_PROFILE: "${ENVIRONMENT}"
    
    
     