import 'modern-normalize/modern-normalize.css';
import "suitcss-base";
//import 'instantsearch.css/themes/reset.css';
import 'instantsearch.css/themes/algolia.css';
import 'intl-tel-input/build/css/intlTelInput.css';
import './css/site.css'; 
import './css/algolia.css'; 
import './css/carousel.css'; 
import './css/login.css'; 
// import './css/signup.css'; 
import './css/imagemodal.css'; 
import './css/tabs.css'; 
import './css/item.css'; 
import './css/offer.css'; 
import './css/megamenu.css';  
import './css/media.css'; 