import './css/site.css'; 
import './css/algolia.css'; 
import './css/carousel.css'; 
import './css/login.css'; 
// import './css/signup.css'; 
import './css/imagemodal.css'; 
import './css/tabs.css'; 
import './css/item.css'; 
import './css/offer.css'; 
import './css/megamenu.css';  
import './css/media.css'; 